export { AdminDashboard } from './Dashboard';
export { Workers } from './Workers';
export { WorkerDetails } from './WorkerDetails';
export { LiveMap } from './LiveMap';
export { Hazards } from './Hazards';
export { SOSCenter } from './SOSCenter';
export { Reports } from './Reports';
export { Notifications } from './Notifications';
export { UserManagement } from './UserManagement';
export { Settings } from './Settings';
export { default as IncidentHistory } from './IncidentHistory';
export { default as Supervisors } from './Supervisors';
export { default as EquipmentIssues } from './EquipmentIssues';
export { default as PPEMonitoring } from './PPEMonitoring';
export { default as SafetyChecklists } from './SafetyChecklists';
export { default as AttendanceShifts } from './AttendanceShifts';
export { default as SafetyScores } from './SafetyScores';
export { default as MineZonesGeofencing } from './MineZonesGeofencing';
export { default as EnvironmentMonitoring } from './EnvironmentMonitoring';
export { default as CommunicationCenter } from './CommunicationCenter';
export { default as Analytics } from './Analytics';
export { AdminLeave } from './AdminLeave';

